In [2]:
import time
import numpy as np


In [3]:
x = np.random.random(1000000)

In [4]:
start = time.time()
sum(x)/len(x)
print(time.time() - start)

0.07686662673950195


In [5]:
start = time.time()
np.mean(x)
print(time.time() - start)

0.04686403274536133


In [6]:
#create 1D array
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [7]:
print(type(x))

<class 'numpy.ndarray'>


In [8]:
x.dtype

dtype('int32')

In [9]:
 x.shape

(5,)

In [11]:
y =np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
y.shape

(4, 3)

In [13]:
y.dtype

dtype('int32')

In [14]:
y.size

12

In [15]:
 x =np.array(['Hello','World'])
 print(x)

['Hello' 'World']


In [18]:
print(x.shape)
print(x.dtype)


(2,)
<U5


In [19]:
#to explicitly specify the datatype of an array
x = np.array([1.5,2,3,5.6],dtype=np.int64)
print(x)
print(x.dtype)

[1 2 3 5]
int64


In [21]:
 #save file to current directory
x =np.array([1,2,3,4,5])
np.save('my_array',x)

In [22]:
#Load the array
y = np.load('my_array.npy')
print(y)

[1 2 3 4 5]


In [25]:
x = np.zeros((3,4),dtype=int)
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [26]:
x.dtype

dtype('int32')

In [27]:
x = np.ones((4,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [28]:
x = np.full((4,3),5)
print(x)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [29]:
x.dtype

dtype('int32')

In [30]:
x = np.eye(5)

In [31]:
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
x =np.diag([10,20,30])
x

array([[10,  0,  0],
       [ 0, 20,  0],
       [ 0,  0, 30]])

In [33]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
x = np.arange(4,10)
print(x)

[4 5 6 7 8 9]


In [35]:
x = np.arange(1,14,3)

In [36]:
x

array([ 1,  4,  7, 10, 13])

In [38]:
x =np.linspace(0,25,10)